apiVersion: v1
kind: Pod
metadata:
  name: formcn-pod2
  namespace: gitops-formcn
  labels:
    app: fromcn-pod2
spec:
  containers:
    - name: message
      image: atbotella/demo:v2
      env:
        - name: CHARACTER
          value: "gitops con Flux sobre cluster K3D"
      resources:
        requests:
          cpu: 10m
          memory: 30Mi
        limits:
          cpu: 10m
          memory: 30Mi
